
version: '3.9'
services:
  movies:
    image: anandkonam/paymovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: anandkonam/paytrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: anandkonam/paydth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: anandkonam/payrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
